### ISSUE TITLE
ClassCastException in org.w3c.css.values.CssColor

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/css-validator#201]
`org.w3c.css.values.CssCalc cannot be cast to org.w3c.css.values.CssNumber` thrown for:

```
foo {
 color: rgba(255,255,255,calc(60/100));
}
```

https://int.samlabs.com/ is a real-world site that currently triggers the same exception:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fint.samlabs.com%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

Stack trace:

```
        at org.w3c.css.values.CssColor.__setRGBAColor(CssColor.java:476)
        at org.w3c.css.values.CssColor.setRGBAColor(CssColor.java:381)
        at org.w3c.css.parser.analyzer.CssParser.function(CssParser.java:6091)
        at org.w3c.css.parser.analyzer.CssParser.term(CssParser.java:5122)
        at org.w3c.css.parser.analyzer.CssParser.expr(CssParser.java:4828)
        at org.w3c.css.parser.analyzer.CssParser.declaration(CssParser.java:4660)
        at org.w3c.css.parser.analyzer.CssParser.declarations(CssParser.java:3421)
        at org.w3c.css.parser.analyzer.CssParser.attributeDeclarations(CssParser.java:3521)
        at org.w3c.css.parser.CssFouffa.parseDeclarations(CssFouffa.java:686)
        at org.w3c.css.css.StyleSheetParser.parseStyleAttribute(StyleSheetParser.java:456)
```

**Comment by ylafon** [comment]
Relative to #51 but a it is very specific case that will require many modifications.

**Comment by ylafon** [comment]
Fixed by the last referenced merge.
